### ISSUE TITLE
Logarithm scales

### ISSUE THREAD

**Issue by marcelocantos** [mathiasbynens/jsperf.com#113]
Some performance charts have large outliers (e.g., http://jsperf.com/indexeddb-vs-localstorage/7), which squashes most of the values against the left edge, making them difficult to distinguish.

It would be good if the author or visitor (or both) could toggle a logarithmic scale in such cases.

**Comment by jdalton** [comment]
Dup of #109, though I like your suggestion a bit better.

**Comment by EamonNerbonne** [comment]
If logarithmic scales are hard, I'd still rather see seconds/op rather than ops/second.  The current scaling is really misleading because it emphasizes small time differences in fast browsers over large time differences in slow browsers.

Also, at the "fast" end of the scale the errors become a lot more significant.  jsperf lists variability scores, but these are almost certainly tricky to interpret since what're you're actually measuring is some distribution of latency values but you're representing the reciprocal thereof, which has a very non-obvious distribution.

**Comment by jdalton** [comment]
Thanks, but I don't see this getting tackled anytime soon.
