### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by lovasoa** [mathiasbynens/jsperf.com#175]
I added a test, and get an internal server error: http://jsperf.com/handling-blobs-in-sql-js

Maybe it's because the test case is quite big (in includes an sqlite database containing an image, stored as a javascript array).

**Comment by YemSalat** [comment]
I got a 500 Internal error for all these tests:

http://jsperf.com/cnvas
http://jsperf.com/cnvas-clear
http://jsperf.com/cnvas-new-clear

They are actually all the same test, but I did not know that they were successfully saved because of the error. The error showed after I created the first test and clicked 'save'
When I went back and tried to save it again - it said that the test slug is already taken (so it did save the test)

To reproduce the error you can go to one of those test, edit it and click 'save'

**Comment by jdalton** [comment]
I got 500 errors all day yesterday, it prevented test revisions from being made. I could edit existing ones, however it would still 500 error, but when I refreshed the edit would stick. I noticed the browserscope charts were taking a while to load too and am wondering if it has anything to do with fetching browserscope tokens/data.

**Comment by mathiasbynens** [comment]
It is due to Browserscope timing out. Not sure what’s up. Maybe @elsigh knows?

**Comment by mathiasbynens** [comment]
Apparently the cause of the issue was an `iptables` misconfiguration on the jsPerf server (out of my hands), where traffic to IPv6-enabled hosts would time out, rather than a Browserscope-specific problem.
