### ISSUE TITLE
/embed (for charts)

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/jsperf.com#20]
Allow embedding test results `iframe`-style (useful for blog posts etc.). Fancy charts!

**Comment by mathiasbynens** [comment]
This already works, but still needs some styling. Or not? http://jsperf.com/slugs/embed

/cc @addyosmani

**Comment by addyosmani** [comment]
Some feedback:

I think it looks fine the way it is right now! :) (there do appear to be some minor layout issues with Canary/Mac, but other than no problems). 

If I did have to change anything, it might be nice to be able to just embed the browserscope results (without the title and filter sections for example, or perhaps just title + browserscope). I don't know if thats beyond the scope of this ticket, but one can imagine jsPerf supporting `/embed/browserscope,title` or `/embed/browserscope` to specify what parts of the page to optionally leave in or out. What do you think?

**Comment by jdalton** [comment]
Is this feature completed?

**Comment by dbkaplun** [comment]
This is broken with `The get/post request has failed :(`: http://jsperf.com/smath-test/11/embed

There is no link to embed from the [JSperf page](http://jsperf.com/smath-test/11) itself.

Also @addyosmani's suggestion is spot on, there is far too much information on the embed page.

Maybe the best thing would be to create an embeddable .png, instead of a full webpage? This would be far more useful as you can't put embeds in Github markdown.
