### ISSUE TITLE
Can not get any test result (in any format)

### ISSUE THREAD

**Issue by belusky** [mathiasbynens/jsperf.com#212]
For example
http://www.browserscope.org/user/tests/table/agt1YS1wcm9maWxlcnIRCxIEVGVzdBiAgIDa5sm3Cww
http://www.browserscope.org/user/tests/table/agt1YS1wcm9maWxlcnINCxIEVGVzdBi1wvoMDA

![image](https://cloud.githubusercontent.com/assets/6204642/5737756/05033d3a-9be5-11e4-8bef-198e14664bef.png)

**Comment by jdalton** [comment]
This looks like a browserscope issue. Pinging @elsigh.

**Comment by elsigh** [comment]
I see an error in the logs but it's not caused by a recent push.. so investigating.

**Comment by elsigh** [comment]
I've updated Browserscope.. thought it seems this test doesn't have results that may have been the issue?  I can pull up results on another few tests ala http://www.browserscope.org/user/tests/table/agt1YS1wcm9maWxlcnINCxIEVGVzdBjk35wVDA?v=3&layout=simple

**Comment by pieroxy** [comment]
Is this issue fixed? Both links in the summary are now working, but BrowserScope stubbornly refuses to display anything on my jsperf since this morning's downtime.

https://jsperf.com/lzstring-1-3-8-vs-1-4-0-forcompress

It's not specific to my test as I cannot see any browserscope info anywhere on any test I clicked so far. I tried on Wifi and 3G so it doesn't seem network related.

**Comment by mathiasbynens** [comment]
Unfortunately, Browserscope doesn’t have TLS set up (e.g. `https://www.browserscope.org/` doesn’t work), so the `iframe` cannot be loaded.

Until Browserscope [fixes this](https://code.google.com/p/browserscope/issues/detail?id=357), try http://jsperf.com/lzstring-1-3-8-vs-1-4-0-forcompress (`http://`, not `https://`).

**Comment by pieroxy** [comment]
Thanks. It works. Everytime I edit my test it switches back to https, but other than that, it works.
