### ISSUE TITLE
Integrate with Google/Twitter accounts

### ISSUE THREAD

**Issue by peol** [mathiasbynens/jsperf.com#38]
Let users login/authenticate themselves using external services. This has several benefits;
- jsperf can load/prefill data using them (doesn't have to be on the same computer, etc.)
- You can automatically attach contact information so users can talk to/contact the author
- A voting system for revisions can be implemented, which could (or hopefully, would) decrease the number of erroneous test cases by showing the "best" revision as default
- Statistics! How many test cases did X or Y do (list all by user etc.), are the tests this user created reliable (propability % by votes etc.)

**Comment by mathiasbynens** [comment]
Thanks for your feedback!

Some comments:

> jsperf can load/prefill data using them (doesn't have to be on the same computer, etc.)

We already store user details in `localStorage` as soon as they’re entered in any form. I’m not sure logging in through an external service would be any faster than just typing your details once.

> You can automatically attach contact information so users can talk to/contact the author

If that’s what the author wants, he’ll add a link to his website or his Twitter account. There’s also a comments section for each test case, just for that :)

> A voting system for revisions can be implemented, which could (or hopefully, would) decrease the number of erroneous test cases by showing the "best" revision as default

Most of the time (?) I end up on a test case because I was given the link. In that case I really want to see that specific revision, not the most popular one. Your suggestion could be applied to the `/browse` and `/search` pages though.

> Statistics! How many test cases did X or Y do (list all by user etc.), are the tests this user created reliable (probability % by votes etc.)

“List all by user” is already possible: http://jsperf.com/faq#author-feed

---

When I created jsPerf I willfully avoided the use of any login system (including a custom-built one that would require registration). “It’s simply not needed for what jsPerf does,” I thought, “it would only make things more complex and add feature creep.”

To be honest, I’m still convinced this is the case… But feel free to convince me :)

**Comment by peol** [comment]
> We already store user details in localStorage as soon as they’re entered in any form. I’m not sure logging in through an external service would be any faster than just typing your details once.

I'm aware of that, however, this is not really feasible if I'm using multiple computers–i.e. my MBP at home and my PC at work, or mobile for that matter.

> If that’s what the author wants, he’ll add a link to his website or his Twitter account. There’s also a comments section for each test case, just for that :)

Correct, I just feel that this would be a nice addition to that–i.e. if you do the integration, just integrate this feature as well :)

> Most of the time (?) I end up on a test case because I was given the link. In that case I really want to see that specific revision, not the most popular one. Your suggestion could be applied to the /browse and /search pages though.

Absolutely, it would be mad to do otherwise. I just meant, what you pointed out, that base URL links (i.e, no revision given) should default to that one.

> “List all by user” is already possible: http://jsperf.com/faq#author-feed

Awesome, didn't know that!
However, that's just an example, the probability stuff would still be great (and any other feature this data would enable)–the author as it is now can easily be faked, right?

> When I created jsPerf I willfully avoided the use of any login system (including a custom-built one that would require registration). “It’s simply not needed for what jsPerf does,” I thought, “it would only make things more complex and add feature creep.”
> 
> To be honest, I’m still convinced this is the case… But feel free to convince me :)

I agree wholeheartedly, and I still want it to feel smooth, quick, and easy to use without a bunch of bloat. However, I don't see this integration as a feature that adds bloat to jsperf, it would just make it easier for people to get started/login, and adds a more streamlined experience cross-devices. Also–this feature request was mainly created because of the anti-cheat/validation argument on the voting-system discussion. :)

**Comment by jdalton** [comment]
At the moment we don't have plans to create a login system.
