### ISSUE TITLE
100% slower! And nothing more...

### ISSUE THREAD

**Issue by sugar700** [mathiasbynens/jsperf.com#79]
Run following test: http://jsperf.com/o#run

For some second test says "100% slower" even if it is slower than this.

**Comment by jdalton** [comment]
Here is how we [currently do it](https://github.com/bestiejs/benchmark.js/blob/master/example/jsperf/ui.js#L582-583):

``` js
percent = Math.round((1 - hz / fastest[0].hz) * 100);
text = isFinite(hz) ? percent + '% slower' : '';
```

so using real numbers (pseudo code) it's

``` js
// 2ops-per-sec / 20 ops-per-sec => 0.1
// 0.1 * 100 => 10% (2 is 10% of 20)
// 1 - 0.1 => 0.9 * 100 => 90% slower
percent = Math.round((1 - (2ops / 20ops) * 100); // 90
text = isFinite(hz) ? percent + '% slower' : ''; // 90% slower
```

Maybe we should calculate how many times slower instead of using a percentage?

**Comment by ainthek** [comment]
hint: @jdalton : analyze browser scope results providing ops per secs if needed .
we do this.

**Comment by psq** [comment]
@jdalton showing how many times slower would be more useful especially in cases such as http://jsperf.com/array-obj-exists

**Comment by jdalton** [comment]
I'm open to PRs but probably won't be tackling this anytime soon.

**Comment by shanimal** [comment]
I found this while confusing "100% slower" and "100 times slower"

In the following example the slowest result is -99.81% slower, but its 548.66 times slower. 

Not that it matters to anyone, but I think the latter is a better measure because -99.81% is a somewhat difficult scale to understand.

![destructuring_overhead_ _jsperf](https://user-images.githubusercontent.com/283957/29227606-50f7dcc4-7e8b-11e7-9607-455a3b1c0f8e.jpg)
https://jsperf.com/destructuring-overhead
